# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openfas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openfas.proto',
  package='openfas',
  syntax='proto3',
  serialized_options=_b('\n\017io.grpc.openfasB\007OpenFasP\001\242\002\003RTG'),
  serialized_pb=_b('\n\ropenfas.proto\x12\x07openfas\"h\n\x05\x46rame\x12\x0f\n\x07\x66rameId\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x01\x12!\n\x05\x64\x65pth\x18\x03 \x01(\x0b\x32\x12.openfas.DepthData\x12\x1d\n\x03rgb\x18\x04 \x01(\x0b\x32\x10.openfas.RGBData\":\n\tDepthData\x12\x0e\n\x06points\x18\x01 \x03(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\"8\n\x07RGBData\x12\x0e\n\x06points\x18\x01 \x03(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\"P\n\x0c\x46rameSummary\x12\x19\n\x11point_cloud_count\x18\x01 \x01(\x05\x12\x0f\n\x07last_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x65lapsed_time\x18\x03 \x01(\x05\x32?\n\x07OpenFas\x12\x34\n\x07PCRoute\x12\x0e.openfas.Frame\x1a\x15.openfas.FrameSummary\"\x00(\x01\x42\"\n\x0fio.grpc.openfasB\x07OpenFasP\x01\xa2\x02\x03RTGb\x06proto3')
)




_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='openfas.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameId', full_name='openfas.Frame.frameId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='openfas.Frame.time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='openfas.Frame.depth', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rgb', full_name='openfas.Frame.rgb', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=130,
)


_DEPTHDATA = _descriptor.Descriptor(
  name='DepthData',
  full_name='openfas.DepthData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='openfas.DepthData.points', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='openfas.DepthData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='openfas.DepthData.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=190,
)


_RGBDATA = _descriptor.Descriptor(
  name='RGBData',
  full_name='openfas.RGBData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='openfas.RGBData.points', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='openfas.RGBData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='openfas.RGBData.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=248,
)


_FRAMESUMMARY = _descriptor.Descriptor(
  name='FrameSummary',
  full_name='openfas.FrameSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point_cloud_count', full_name='openfas.FrameSummary.point_cloud_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_id', full_name='openfas.FrameSummary.last_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsed_time', full_name='openfas.FrameSummary.elapsed_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=330,
)

_FRAME.fields_by_name['depth'].message_type = _DEPTHDATA
_FRAME.fields_by_name['rgb'].message_type = _RGBDATA
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['DepthData'] = _DEPTHDATA
DESCRIPTOR.message_types_by_name['RGBData'] = _RGBDATA
DESCRIPTOR.message_types_by_name['FrameSummary'] = _FRAMESUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'openfas_pb2'
  # @@protoc_insertion_point(class_scope:openfas.Frame)
  ))
_sym_db.RegisterMessage(Frame)

DepthData = _reflection.GeneratedProtocolMessageType('DepthData', (_message.Message,), dict(
  DESCRIPTOR = _DEPTHDATA,
  __module__ = 'openfas_pb2'
  # @@protoc_insertion_point(class_scope:openfas.DepthData)
  ))
_sym_db.RegisterMessage(DepthData)

RGBData = _reflection.GeneratedProtocolMessageType('RGBData', (_message.Message,), dict(
  DESCRIPTOR = _RGBDATA,
  __module__ = 'openfas_pb2'
  # @@protoc_insertion_point(class_scope:openfas.RGBData)
  ))
_sym_db.RegisterMessage(RGBData)

FrameSummary = _reflection.GeneratedProtocolMessageType('FrameSummary', (_message.Message,), dict(
  DESCRIPTOR = _FRAMESUMMARY,
  __module__ = 'openfas_pb2'
  # @@protoc_insertion_point(class_scope:openfas.FrameSummary)
  ))
_sym_db.RegisterMessage(FrameSummary)


DESCRIPTOR._options = None

_OPENFAS = _descriptor.ServiceDescriptor(
  name='OpenFas',
  full_name='openfas.OpenFas',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=332,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='PCRoute',
    full_name='openfas.OpenFas.PCRoute',
    index=0,
    containing_service=None,
    input_type=_FRAME,
    output_type=_FRAMESUMMARY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPENFAS)

DESCRIPTOR.services_by_name['OpenFas'] = _OPENFAS

# @@protoc_insertion_point(module_scope)
